name: responsi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  # Perbaikan: Ubah dari ^3.9.2 menjadi ^3.9.0 agar cocok dengan SDK Anda
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0           # Untuk akses API [cite: 30]
  shared_preferences: ^2.2.2 # Untuk Login session 
  url_launcher: ^6.2.4   # Untuk tombol "Read more" 
  intl: ^0.19.0          # Untuk format tanggal
  provider: ^6.1.1       # Untuk state management Favorites

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true